[package]
name = "tiny-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tiny-serde-macros = { path = "/Users/adinack/Projects/tiny-serde-macros" }

