[package]
name = "tiny-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tiny-serde-macros = { git = "https://github.com/AdinAck/tiny-serde-macros", branch = "main" }

