[package]
name = "tiny-serde"
version = "0.1.0"
edition = "2021"

[features]
default = ["derive", "unsafe"]
derive = ["dep:macros"]
unsafe = ["macros/unsafe"]

[dependencies]
macros = { path = "../macros", optional = true }
